[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mlora"
version = "0.2"
description = "A tool for fine-tuning large language models (LLMs) using the LoRA or QLoRA methods more efficiently."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch==2.0.1",
    "einops==0.6.1",
    "datasets==2.14.5",
    "evaluate==0.4.1",
    "accelerate==0.24.1",
    "transformers==4.36.2",
    "bitsandbytes==0.41.1",
    "sentencepiece==0.1.99",
    "scipy==1.10.1",
    "protobuf==3.20.2",
    "xformers==0.0.21",
    "huggingface_hub",
    "scikit-learn",
]

[project.urls]
"Homepage" = "https://github.com/mikecovlee/mlora"
"Bug Tracker" = "https://github.com/mikecovlee/mlora/issues"

[tool.setuptools.packages.find]
include = ["mlora"]
